### ISSUE TITLE
sdk pointing to which API version of drift ?

### ISSUE THREAD

**Issue by FirojNeosoft** [Driftt/drift-python#16]
I used get method of contacts, but I got result which does not match with contact object that given in API 1.4 doc of drift, like I got key "last_name" instead of "name".
Therefore I want to know that which API version of drift used for this sdk ?

**Comment by natehoffy** [comment]
Hey FirojNeosoft, Might be using a weird / deprecated endpoint without intending too. We had some support for this drop off, but trying to get back into it more consistently. What endpoint is giving you grief on this?

**Comment by natehoffy** [comment]
Updating: there is currently only 1 version of Drift. This wrapper points to that version: latest.
